# COMANDOS PYTHON
x = 0 # VARIÁVEIS
input() # SOLICITA UM COMANDO
print() # MOSTRA NA TELA 
int() # USADO PARA NÚMEORS INTEIROS
str() # USADO PARA UMA CADEIA DE CARACTERES
float() # USADO PARA NÚMEROS DECIMAIS
    if: # CRITERIO (SE)
    else: # CRITERIO (SE NÃO)
for i in range(): # ESTRUTURA DE REPETIÇÃO FINITA - É DEFINIDO PELO NÚMERO ARMAZENADO DENTRO DO PARENTESSE  
while  # ESTRUTURA DE REPETIÇÃO INFINITA
      